name: 11.0.xw64

on:
  workflow_dispatch:
    branches:
      - master

jobs:
  xwayland64:
    uses: vanilla-dpup/woof-CE/.github/workflows/build.yml@vanilladpup-11.0.x
    with:
      repo: vanilla-dpup/woof-CE
      ref: vanilladpup-11.0.x
      name: "Vanilla Dpup"
      version: 11.0.${{ github.run_number }}
      arch: x86_64
      compat-distro: debian
      compat-distro-version: trixie64
      kernel: debian-trixie
      prefix: vanilladpup
      artifact: vanilladpup-x86_64-11.0.${{ github.run_number }}-xwayland
      retention: 1
      variant: xwayland
  upload64:
    needs: [xwayland64]
    runs-on: ubuntu-22.04
    steps:
      - name: Download xwayland build artifact
        uses: actions/download-artifact@v4
        with:
          name: vanilladpup-x86_64-11.0.${{ github.run_number }}-xwayland
          path: xwayland
      - name: Rename ISO
        run: |
          mv -f xwayland/*.iso vanilladpup-11.0.${{ github.run_number }}-xwayland.iso
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: vanilladpup-x86_64-11.0.${{ github.run_number }}
          tag_name: vanilladpup-x86_64-11.0.${{ github.run_number }}
          fail_on_unmatched_files: true
          files: |
            *.iso
  cleanup:
    needs: [upload64]
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        arch: [x86_64]
    steps:
      - name: Delete old ${{ matrix.arch }} releases
        uses: dev-drprasad/delete-older-releases@v0.3.4
        with:
          keep_latest: 1
          delete_tag_pattern: vanilladpup-${{ matrix.arch }}-11.0.
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
